library(Ropendal)

helper <- system.file("tinytest", "helper-ropendal.R", package = "Ropendal")
source(helper, local = TRUE)

root <- ropendal_temp_root()
cache_dir <- ropendal_temp_root()
fs <- opendal("fs", root = root)
store <- byte_store(fs, "chunks")

expect_true(identical(store_write(store, "c/0", as.raw(c(1, 2, 3))), TRUE))
cached <- store_cache(store, cache_dir, validate = "last_modified_size")
expect_true(inherits(cached, "ropendalCachedByteStore"))
expect_error(store_cache(cached, cache_dir), "already cached")
expect_error(store_cache(store, ""), "cache_dir")

expect_equal(as.raw(store_read(cached, "c/0")), as.raw(c(1, 2, 3)))
expect_true(identical(store_replace(store, "c/0", as.raw(c(4, 5, 6, 7))), TRUE))
expect_equal(as.raw(store_read(cached, "c/0")), as.raw(c(4, 5, 6, 7)))
bytes <- store_read(cached, "c/0")
expect_true(inherits(bytes, "OpendalBytes"))
expect_equal(as.raw(bytes), as.raw(c(4, 5, 6, 7)))

expect_true(identical(store_write(store, "c/1", as.raw(c(9, 8))), TRUE))
expect_equal(
  lapply(store_read(cached, c("c/0", "c/1")), as.raw),
  list(as.raw(c(4, 5, 6, 7)), as.raw(c(9, 8)))
)
expect_equal(as.raw(collect_aio(store_read_aio(cached, "c/0"))), as.raw(c(4, 5, 6, 7)))
expect_equal(collect_aio(store_read_aio(cached, "c/0", mode = "raw")), as.raw(c(4, 5, 6, 7)))
expect_equal(as.raw(store_read(cached, "c/0", offset = 1, size = 2)), as.raw(c(5, 6)))
expect_equal(lapply(store_read(cached, "c/0", result = "flat"), as.raw), list(as.raw(c(4, 5, 6, 7))))

expect_true(identical(store_replace(store, "large.bin", as.raw(1:6)), TRUE))
block_cached <- store_block_cache(store, ropendal_temp_root(), block_size = 2)
expect_true(inherits(block_cached, "ropendalBlockCachedByteStore"))
expect_error(store_block_cache(block_cached, ropendal_temp_root()), "already cached")
expect_error(store_block_cache(store, ropendal_temp_root(), block_size = 0), "positive")
expect_equal(as.raw(store_read(block_cached, "large.bin", offset = 1, size = 4)), as.raw(2:5))
expect_equal(store_read(block_cached, "large.bin", offset = 2, size = 3, mode = "raw"), as.raw(3:5))
expect_equal(as.raw(collect_aio(store_read_aio(block_cached, "large.bin", offset = 1, size = 3))), as.raw(2:4))
expect_equal(collect_aio(store_read_aio(block_cached, "large.bin", offset = 2, size = 3, mode = "raw")), as.raw(3:5))
block_key <- getFromNamespace(".ropendal_block_cache_object_key", "Ropendal")(0, block_cached, "large.bin")
expect_true(identical(store_replace(block_cached$cache_store, block_key, as.raw(99)), TRUE))
expect_equal(as.raw(collect_aio(store_read_aio(block_cached, "large.bin", offset = 0, size = 2))), as.raw(1:2))
block_key <- getFromNamespace(".ropendal_block_cache_object_key", "Ropendal")(1, block_cached, "large.bin")
expect_true(identical(store_replace(block_cached$cache_store, block_key, as.raw(99)), TRUE))
expect_equal(as.raw(store_read(block_cached, "large.bin", offset = 1, size = 4)), as.raw(2:5))
expect_true(identical(store_replace(store, "large.bin", as.raw(c(9, 8, 7))), TRUE))
expect_equal(as.raw(store_read(block_cached, "large.bin", offset = 0, size = 3)), as.raw(c(9, 8, 7)))
block_cached_none <- store_block_cache(store, ropendal_temp_root(), block_size = 2, validate = "none")
expect_equal(as.raw(store_read(block_cached_none, "large.bin", offset = 0, size = 2)), as.raw(c(9, 8)))
expect_true(identical(store_replace(store, "large.bin", as.raw(c(1, 2, 3))), TRUE))
expect_equal(as.raw(store_read(block_cached_none, "large.bin", offset = 0, size = 2)), as.raw(c(9, 8)))
expect_equal(lapply(store_read(block_cached_none, "large.bin", result = "flat"), as.raw), list(as.raw(c(1, 2, 3))))
expect_equal(store_read(block_cached_none, "large.bin", offset = c(0, 2), size = c(1, 1), result = "flat", mode = "raw"), list(as.raw(1), as.raw(3)))
expect_true(identical(store_replace(store, "large.bin", as.raw(c(7, 6, 5, 4))), TRUE))
expect_equal(collect_aio(store_read_aio(block_cached_none, "large.bin", mode = "raw")), as.raw(c(7, 6, 5, 4)))
expect_equal(collect_aio(store_read_aio(block_cached_none, "large.bin", offset = 99, size = 10, mode = "raw")), raw(0))
expect_equal(as.raw(store_read(block_cached_none, "large.bin")), as.raw(c(7, 6, 5, 4)))
expect_true(identical(store_replace(store, "cycle.bin", as.raw(1:4)), TRUE))
block_cached_cycle <- store_block_cache(store, ropendal_temp_root(), block_size = 2, validate = "none")
expect_equal(as.raw(store_read(block_cached_cycle, "cycle.bin", offset = 0, size = 4)), as.raw(1:4))
expect_true(identical(store_replace(store, "cycle.bin", as.raw(c(9, 8))), TRUE))
expect_equal(as.raw(store_read(block_cached_cycle, "cycle.bin", offset = 0, size = 2)), as.raw(c(9, 8)))
expect_true(identical(store_replace(store, "cycle.bin", as.raw(c(5, 6, 7, 8))), TRUE))
expect_equal(as.raw(store_read(block_cached_cycle, "cycle.bin", offset = 2, size = 2)), as.raw(c(7, 8)))
expect_true(identical(store_replace(store, "cycle-miss.bin", as.raw(1:4)), TRUE))
block_cached_miss <- store_block_cache(store, ropendal_temp_root(), block_size = 2, validate = "none")
expect_equal(as.raw(store_read(block_cached_miss, "cycle-miss.bin", offset = 0, size = 4)), as.raw(1:4))
block_key <- getFromNamespace(".ropendal_block_cache_object_key", "Ropendal")(1, block_cached_miss, "cycle-miss.bin")
expect_true(identical(store_delete(block_cached_miss$cache_store, block_key), TRUE))
expect_true(identical(store_replace(store, "cycle-miss.bin", as.raw(c(9, 8))), TRUE))
expect_true(identical(store_replace(store, "cycle-miss.bin", as.raw(c(5, 6, 7, 8))), TRUE))
expect_equal(collect_aio(store_read_aio(block_cached_miss, "cycle-miss.bin", mode = "raw")), as.raw(c(5, 6, 7, 8)))
expect_true(identical(store_replace(store, "lm-miss.bin", as.raw(1:4)), TRUE))
block_cached_lm <- store_block_cache(store, ropendal_temp_root(), block_size = 2)
expect_equal(as.raw(store_read(block_cached_lm, "lm-miss.bin", offset = 0, size = 4)), as.raw(1:4))
block_key <- getFromNamespace(".ropendal_block_cache_object_key", "Ropendal")(1, block_cached_lm, "lm-miss.bin")
expect_true(identical(store_delete(block_cached_lm$cache_store, block_key), TRUE))
expect_true(identical(store_replace(store, "lm-miss.bin", as.raw(c(5, 6, 7, 8))), TRUE))
expect_equal(store_read(block_cached_lm, "lm-miss.bin", offset = 0, size = 4, mode = "raw"), as.raw(c(5, 6, 7, 8)))
expect_true(identical(store_replace(block_cached_none, "large.bin", as.raw(c(4, 5, 6))), TRUE))
expect_equal(as.raw(store_read(block_cached_none, "large.bin", offset = 0, size = 3)), as.raw(c(4, 5, 6)))
expect_true(identical(store_cache_clear(block_cached_none), TRUE))

cache_dir_none <- ropendal_temp_root()
cached_none <- store_cache(store, cache_dir_none, validate = "none")
expect_equal(as.raw(store_read(cached_none, "c/0")), as.raw(c(4, 5, 6, 7)))
expect_true(identical(store_replace(store, "c/0", as.raw(10)), TRUE))
expect_equal(as.raw(store_read(cached_none, "c/0")), as.raw(c(4, 5, 6, 7)))
expect_true(identical(store_replace(cached_none, "c/0", as.raw(11)), TRUE))
expect_equal(as.raw(store_read(cached_none, "c/0")), as.raw(11))
expect_equal(as.raw(store_read(store, "c/0")), as.raw(11))

expect_true(identical(store_write(cached_none, "new", as.raw(12)), TRUE))
expect_equal(as.raw(store_read(cached_none, "new")), as.raw(12))
expect_true(is_error_value(store_write(cached_none, "new", as.raw(13))))
expect_true(identical(collect_aio(store_replace_aio(cached_none, "new", as.raw(14))), TRUE))
expect_equal(as.raw(store_read(cached_none, "new")), as.raw(14))
expect_true(identical(collect_aio(store_write_aio(cached_none, "new-aio", as.raw(15))), TRUE))
expect_equal(as.raw(collect_aio(store_read_aio(cached_none, "new-aio"))), as.raw(15))
expect_true(collect_aio(store_exists_aio(cached_none, "new-aio")))
expect_true(identical(collect_aio(store_delete_aio(cached_none, "new-aio")), TRUE))
expect_false(store_exists(cached_none, "new-aio"))

expect_true(identical(store_delete(cached_none, "new"), TRUE))
expect_false(store_exists(cached_none, "new"))
missing <- store_read(cached_none, "new")
expect_true(is_error_value(missing))
expect_equal(error_kind(missing), "NotFound")

expect_true(identical(store_write(store, "dir/a", as.raw(1)), TRUE))
expect_true(identical(store_write(store, "dir/b", as.raw(2)), TRUE))
expect_true(identical(store_delete(cached_none, "dir/", recursive = TRUE), TRUE))
expect_false(store_exists(cached_none, "dir/a"))
expect_true(identical(store_cache_clear(cached_none), TRUE))

entries <- store_list(cached, recursive = TRUE)
paths <- vapply(entries, `[[`, character(1), "path")
expect_true("c/0" %in% paths)
expect_false(any(startsWith(paths, "chunks/")))
