#!/usr/bin/env Rscript

pkg_root <- system.file(package = "Ropendal")
if (!nzchar(pkg_root)) stop("Ropendal is not installed", call. = FALSE)
library(Ropendal)
header <- system.file("include", "ropendal.h", package = "Ropendal")
lib_dir <- system.file("libs", package = "Ropendal")
lib <- file.path(lib_dir, paste0("Ropendal", .Platform$dynlib.ext))
if (!file.exists(header)) stop("installed header not found", call. = FALSE)
if (!file.exists(lib)) stop("installed native library not found", call. = FALSE)

cc_candidates <- c(Sys.getenv("CC", unset = ""), Sys.which(c("cc", "gcc", "clang")))
cc_candidates <- cc_candidates[nzchar(cc_candidates)]
if (!length(cc_candidates)) stop("no C compiler found", call. = FALSE)
cc <- cc_candidates[[1L]]

src <- tempfile("ropendal-c-api-roundtrip-", fileext = ".c")
exe <- tempfile("ropendal-c-api-roundtrip-")
root <- tempfile("ropendal-c-api-root-")
dir.create(root, recursive = TRUE)

writeLines(c(
  '#include "ropendal.h"',
  '#include <stdatomic.h>',
  '#include <stdint.h>',
  '#include <stdio.h>',
  '#include <string.h>',
  '',
  'struct callback_state {',
  '  ropendal_cv_t *cv;',
  '  atomic_uintptr_t aio_addr;',
  '  atomic_int called;',
  '};',
  '',
  'static void capture_callback(ropendal_aio_t *aio, void *userdata) {',
  '  struct callback_state *state = (struct callback_state *)userdata;',
  '  atomic_store(&state->aio_addr, (uintptr_t)aio);',
  '  atomic_fetch_add(&state->called, 1);',
  '  ropendal_cv_signal(state->cv);',
  '}',
  '',
  'static int fail(const char *msg, const ropendal_error_t *err) {',
  '  if (err != 0) {',
  '    const char *kind = ropendal_error_kind(err);',
  '    const char *text = ropendal_error_message(err);',
  '    fprintf(stderr, "%s: %s %s\\n", msg, kind ? kind : "", text ? text : "");',
  '  } else {',
  '    fprintf(stderr, "%s\\n", msg);',
  '  }',
  '  return 1;',
  '}',
  '',
  'int main(int argc, char **argv) {',
  '  if (argc != 3) return fail("missing root or fixture endpoint", 0);',
  '  ropendal_fs_t *fs = 0;',
  '  ropendal_aio_t *aio = 0;',
  '  ropendal_error_t *err = 0;',
  '  ropendal_kv_t kv = {0};',
  '  kv.struct_size = sizeof kv;',
  '  kv.key = "root";',
  '  kv.value = argv[1];',
  '  int st = ropendal_fs_open("fs", &kv, 1, &fs, &err);',
  '  if (st != ROPENDAL_OK) return fail("open failed", err);',
  '',
  '  ropendal_cv_t *cv = 0;',
  '  st = ropendal_cv_alloc(&cv, &err);',
  '  if (st != ROPENDAL_OK) return fail("cv alloc failed", err);',
  '  if (ropendal_cv_value(cv) != 0) return fail("unexpected initial cv value", 0);',
  '  ropendal_cv_signal(cv);',
  '  if (ropendal_cv_value(cv) != 1) return fail("unexpected signalled cv value", 0);',
  '  ropendal_cv_reset(cv);',
  '  if (ropendal_cv_value(cv) != 0) return fail("unexpected reset cv value", 0);',
  '  st = ropendal_cv_until(cv, 1, &err);',
  '  if (st != ROPENDAL_OK) return fail("cv until failed", err);',
  '  ropendal_cv_release(cv);',
  '',
  '  const uint8_t codec_src[5] = {10, 20, 30, 40, 50};',
  '  ropendal_bytes_t *encoded = 0;',
  '  ropendal_bytes_t *decoded = 0;',
  '  st = ropendal_codec_encode("gzip", codec_src, sizeof codec_src, &encoded, &err);',
  '  if (st != ROPENDAL_OK) return fail("codec encode failed", err);',
  '  const uint8_t *encoded_data = ropendal_bytes_data(encoded);',
  '  size_t encoded_len = ropendal_bytes_len(encoded);',
  '  if (encoded_len < 2 || encoded_data == 0 || encoded_data[0] != 0x1f || encoded_data[1] != 0x8b) return fail("unexpected gzip bytes", 0);',
  '  st = ropendal_codec_decode("gzip", encoded_data, encoded_len, &decoded, &err);',
  '  if (st != ROPENDAL_OK) return fail("codec decode failed", err);',
  '  if (ropendal_bytes_len(decoded) != sizeof codec_src || memcmp(ropendal_bytes_data(decoded), codec_src, sizeof codec_src) != 0) return fail("unexpected codec roundtrip", 0);',
  '  ropendal_bytes_release(encoded);',
  '  ropendal_bytes_release(decoded);',
  '  st = ropendal_codec_encode("brotli", codec_src, sizeof codec_src, &encoded, &err);',
  '  if (st != ROPENDAL_UNSUPPORTED) return fail("unsupported codec did not report unsupported", err);',
  '  ropendal_error_release(err);',
  '  err = 0;',
  '',
  '  ropendal_store_t *store = 0;',
  '  ropendal_store_options_t so = {0};',
  '  so.struct_size = sizeof so;',
  '  so.prefix = "cstore";',
  '  st = ropendal_store_open(fs, &so, &store, &err);',
  '  if (st != ROPENDAL_OK) return fail("store open failed", err);',
  '  ropendal_store_retain(store);',
  '  ropendal_store_release(store);',
  '  const uint8_t store_src[5] = {9, 8, 7, 6, 5};',
  '  ropendal_store_write_options_t sw = {0};',
  '  sw.struct_size = sizeof sw;',
  '  sw.key = "nested/item.bin";',
  '  sw.part_concurrency = 1;',
  '  sw.chunk_size = 2;',
  '  aio = 0;',
  '  st = ropendal_store_write_aio(store, &sw, store_src, sizeof store_src, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store write submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store write wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  ropendal_store_read_options_t sr = {0};',
  '  sr.struct_size = sizeof sr;',
  '  sr.key = "nested/item.bin";',
  '  sr.has_offset = 1;',
  '  sr.offset = 1;',
  '  sr.has_size = 1;',
  '  sr.size = 3;',
  '  sr.part_concurrency = 1;',
  '  sr.chunk_size = 2;',
  '  aio = 0;',
  '  st = ropendal_store_read_aio(store, &sr, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read wait failed", err);',
  '  const uint8_t *store_bytes = 0;',
  '  size_t store_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &store_bytes, &store_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read result failed", err);',
  '  if (store_len != 3 || store_bytes == 0 || store_bytes[0] != 8 || store_bytes[2] != 6) return fail("unexpected store range bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  uint8_t store_dst[2] = {0, 0};',
  '  sr.offset = 2;',
  '  sr.size = 2;',
  '  aio = 0;',
  '  st = ropendal_store_read_into_aio(store, &sr, store_dst, sizeof store_dst, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read_into submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read_into wait failed", err);',
  '  size_t store_nread = 0;',
  '  st = ropendal_aio_result_nread(aio, &store_nread, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read_into nread failed", err);',
  '  if (store_nread != 2 || store_dst[0] != 7 || store_dst[1] != 6) return fail("unexpected store read_into bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  const uint8_t store_repl[5] = {5, 4, 3, 2, 1};',
  '  aio = 0;',
  '  st = ropendal_store_replace_aio(store, &sw, store_repl, sizeof store_repl, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store replace submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store replace wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  sr.offset = 0;',
  '  sr.size = 2;',
  '  aio = 0;',
  '  st = ropendal_store_read_aio(store, &sr, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read after replace submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read after replace wait failed", err);',
  '  store_bytes = 0;',
  '  store_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &store_bytes, &store_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("store read after replace result failed", err);',
  '  if (store_len != 2 || store_bytes == 0 || store_bytes[0] != 5 || store_bytes[1] != 4) return fail("unexpected store replace bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_store_t *cache_store = 0;',
  '  ropendal_store_t *cached_store = 0;',
  '  ropendal_store_options_t cache_so = {0};',
  '  cache_so.struct_size = sizeof cache_so;',
  '  cache_so.prefix = "cstore-cache";',
  '  st = ropendal_store_open(fs, &cache_so, &cache_store, &err);',
  '  if (st != ROPENDAL_OK) return fail("cache store open failed", err);',
  '  ropendal_store_cache_options_t sc = {0};',
  '  sc.struct_size = sizeof sc;',
  '  st = ropendal_store_cache_open(store, cache_store, &sc, &cached_store, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store open failed", err);',
  '  ropendal_store_read_options_t scr = {0};',
  '  scr.struct_size = sizeof scr;',
  '  scr.key = "nested/item.bin";',
  '  aio = 0;',
  '  st = ropendal_store_read_aio(cached_store, &scr, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store read wait failed", err);',
  '  store_bytes = 0;',
  '  store_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &store_bytes, &store_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store read result failed", err);',
  '  if (store_len != 5 || store_bytes == 0 || store_bytes[0] != 5 || store_bytes[4] != 1) return fail("unexpected cached store fill bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  const uint8_t store_short[2] = {1, 0};',
  '  aio = 0;',
  '  st = ropendal_store_replace_aio(store, &sw, store_short, sizeof store_short, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("direct store replace before cache validation submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("direct store replace before cache validation wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  aio = 0;',
  '  st = ropendal_store_read_aio(cached_store, &scr, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store validation read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store validation read wait failed", err);',
  '  store_bytes = 0;',
  '  store_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &store_bytes, &store_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store validation read result failed", err);',
  '  if (store_len != 2 || store_bytes == 0 || store_bytes[0] != 1 || store_bytes[1] != 0) return fail("cached store validation did not refresh", 0);',
  '  ropendal_aio_release(aio);',
  '  aio = 0;',
  '  st = ropendal_store_replace_aio(cached_store, &sw, store_repl, sizeof store_repl, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store replace submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("cached store replace wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  ropendal_store_release(cached_store);',
  '  ropendal_store_release(cache_store);',
  '  aio = 0;',
  '  st = ropendal_store_exists_aio(store, "nested/item.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store exists submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store exists wait failed", err);',
  '  int store_exists = 0;',
  '  st = ropendal_aio_result_bool(aio, &store_exists, &err);',
  '  if (st != ROPENDAL_OK) return fail("store exists result failed", err);',
  '  if (!store_exists) return fail("store object did not exist", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_store_ls_options_t sl = {0};',
  '  sl.struct_size = sizeof sl;',
  '  sl.path = "";',
  '  sl.recursive = 1;',
  '  aio = 0;',
  '  st = ropendal_store_ls_aio(store, &sl, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store ls submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store ls wait failed", err);',
  '  const ropendal_entry_t *store_entries = 0;',
  '  size_t store_entries_len = 0;',
  '  st = ropendal_aio_result_entries(aio, &store_entries, &store_entries_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("store ls result failed", err);',
  '  int saw_store_item = 0;',
  '  for (size_t i = 0; i < store_entries_len; ++i) {',
  '    if (store_entries[i].path != 0 && strcmp(store_entries[i].path, "nested/item.bin") == 0) saw_store_item = 1;',
  '  }',
  '  if (!saw_store_item) return fail("store ls did not return relative key", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_store_delete_options_t sd = {0};',
  '  sd.struct_size = sizeof sd;',
  '  sd.key = "nested/";',
  '  sd.recursive = 1;',
  '  aio = 0;',
  '  st = ropendal_store_delete_aio(store, &sd, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store delete submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store delete wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  aio = 0;',
  '  st = ropendal_store_exists_aio(store, "nested/item.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("store exists after delete submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("store exists after delete wait failed", err);',
  '  st = ropendal_aio_result_bool(aio, &store_exists, &err);',
  '  if (st != ROPENDAL_OK) return fail("store exists after delete result failed", err);',
  '  if (store_exists) return fail("store object still existed after delete", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_store_release(store);',
  '',
  '  const uint8_t src[4] = {1, 2, 3, 4};',
  '  ropendal_write_options_t w = {0};',
  '  w.struct_size = sizeof w;',
  '  w.path = "a.bin";',
  '  w.part_concurrency = 1;',
  '  w.chunk_size = 2;',
  '  st = ropendal_write_aio(fs, &w, src, sizeof src, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("write submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("write wait failed", err);',
  '  ropendal_aio_release(aio);',
  '',
  '  ropendal_cv_t *callback_cv = 0;',
  '  struct callback_state cb_state = {0};',
  '  st = ropendal_cv_alloc(&callback_cv, &err);',
  '  if (st != ROPENDAL_OK) return fail("callback cv alloc failed", err);',
  '  cb_state.cv = callback_cv;',
  '  atomic_init(&cb_state.aio_addr, (uintptr_t)0);',
  '  atomic_init(&cb_state.called, 0);',
  '  ropendal_read_options_t callback_r = {0};',
  '  callback_r.struct_size = sizeof callback_r;',
  '  callback_r.path = "a.bin";',
  '  callback_r.callback = capture_callback;',
  '  callback_r.userdata = &cb_state;',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &callback_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("callback read submit failed", err);',
  '  for (int i = 0; i < 100 && atomic_load(&cb_state.called) == 0; ++i) {',
  '    st = ropendal_cv_until(callback_cv, 10, &err);',
  '    if (st != ROPENDAL_OK) return fail("callback cv until failed", err);',
  '  }',
  '  if (atomic_load(&cb_state.called) != 1 || (ropendal_aio_t *)atomic_load(&cb_state.aio_addr) != aio) return fail("callback did not receive completed aio", 0);',
  '  if (ropendal_aio_poll(aio) != ROPENDAL_AIO_READY) return fail("callback aio was not ready", 0);',
  '  const uint8_t *callback_bytes = 0;',
  '  size_t callback_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &callback_bytes, &callback_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("callback result failed", err);',
  '  if (callback_len != 4 || callback_bytes == 0 || callback_bytes[0] != 1 || callback_bytes[3] != 4) return fail("unexpected callback bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_cv_release(callback_cv);',
  '',
  '  ropendal_cv_t *release_cv = 0;',
  '  struct callback_state release_state = {0};',
  '  st = ropendal_cv_alloc(&release_cv, &err);',
  '  if (st != ROPENDAL_OK) return fail("release callback cv alloc failed", err);',
  '  release_state.cv = release_cv;',
  '  atomic_init(&release_state.aio_addr, (uintptr_t)0);',
  '  atomic_init(&release_state.called, 0);',
  '  callback_r.userdata = &release_state;',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &callback_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("release callback read submit failed", err);',
  '  uintptr_t released_aio_addr = (uintptr_t)aio;',
  '  ropendal_aio_release(aio);',
  '  for (int i = 0; i < 100 && atomic_load(&release_state.called) == 0; ++i) {',
  '    st = ropendal_cv_until(release_cv, 10, &err);',
  '    if (st != ROPENDAL_OK) return fail("release callback cv until failed", err);',
  '  }',
  '  if (atomic_load(&release_state.called) != 1 || atomic_load(&release_state.aio_addr) != released_aio_addr) return fail("release callback did not retain aio", 0);',
  '  ropendal_cv_release(release_cv);',
  '',
  '  ropendal_write_options_t unsupported_w = {0};',
  '  unsupported_w.struct_size = sizeof unsupported_w;',
  '  unsupported_w.path = "unsupported.bin";',
  '  unsupported_w.content_type = "application/octet-stream";',
  '  aio = 0;',
  '  st = ropendal_replace_aio(fs, &unsupported_w, src, sizeof src, &aio, &err);',
  '  if (st != ROPENDAL_UNSUPPORTED) return fail("unsupported write option did not fail", err);',
  '  if (aio != 0) return fail("unsupported write option returned aio", 0);',
  '  ropendal_error_release(err);',
  '  err = 0;',
  '  ropendal_read_options_t positive_wait_r = {0};',
  '  positive_wait_r.struct_size = sizeof positive_wait_r;',
  '  positive_wait_r.path = "a.bin";',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &positive_wait_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("positive-timeout read submit failed", err);',
  '  st = ropendal_aio_wait(aio, 1000, &err);',
  '  if (st != ROPENDAL_OK) return fail("positive-timeout wait failed", err);',
  '  ropendal_aio_release(aio);',
  '',
  '  ropendal_cv_t *notify_cv = 0;',
  '  st = ropendal_cv_alloc(&notify_cv, &err);',
  '  if (st != ROPENDAL_OK) return fail("notify cv alloc failed", err);',
  '  ropendal_read_options_t notify_r = {0};',
  '  notify_r.struct_size = sizeof notify_r;',
  '  notify_r.path = "a.bin";',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &notify_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("notify read submit failed", err);',
  '  st = ropendal_aio_notify(aio, notify_cv, 7, &err);',
  '  if (st != ROPENDAL_OK) return fail("aio notify failed", err);',
  '  for (int i = 0; i < 100 && ropendal_cv_value(notify_cv) == 0; ++i) {',
  '    st = ropendal_cv_until(notify_cv, 10, &err);',
  '    if (st != ROPENDAL_OK) return fail("notify cv until failed", err);',
  '  }',
  '  if (ropendal_cv_value(notify_cv) == 0) return fail("aio notify did not signal", 0);',
  '  const uint8_t *notify_bytes = 0;',
  '  size_t notify_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &notify_bytes, &notify_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("notify result failed", err);',
  '  if (notify_len != 4 || notify_bytes == 0 || notify_bytes[0] != 1 || notify_bytes[3] != 4) return fail("unexpected notify bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_cv_release(notify_cv);',
  '',
  '  ropendal_cv_t *monitor_cv = 0;',
  '  ropendal_monitor_t *monitor = 0;',
  '  st = ropendal_cv_alloc(&monitor_cv, &err);',
  '  if (st != ROPENDAL_OK) return fail("monitor cv alloc failed", err);',
  '  st = ropendal_monitor_create(monitor_cv, &monitor, &err);',
  '  if (st != ROPENDAL_OK) return fail("monitor create failed", err);',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &notify_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("monitor read submit failed", err);',
  '  st = ropendal_monitor_add_aio(monitor, aio, 42, &err);',
  '  if (st != ROPENDAL_OK) return fail("monitor add aio failed", err);',
  '  const ropendal_monitor_event_t *events = 0;',
  '  size_t nevents = 0;',
  '  for (int i = 0; i < 100; ++i) {',
  '    st = ropendal_monitor_read(monitor, &events, &nevents, &err);',
  '    if (st != ROPENDAL_OK) return fail("monitor read failed", err);',
  '    if (nevents > 0) break;',
  '    st = ropendal_cv_until(monitor_cv, 10, &err);',
  '    if (st != ROPENDAL_OK) return fail("monitor cv until failed", err);',
  '  }',
  '  if (nevents != 1 || events == 0) return fail("monitor did not report one event", 0);',
  '  if (events[0].kind != ROPENDAL_EVENT_AIO_READY || events[0].id != 42 || events[0].aio != aio) return fail("unexpected monitor event", 0);',
  '  notify_bytes = 0; notify_len = 0;',
  '  st = ropendal_aio_result_bytes(aio, &notify_bytes, &notify_len, &err);',
  '  if (st != ROPENDAL_OK) return fail("monitor aio result failed", err);',
  '  if (notify_len != 4 || notify_bytes == 0 || notify_bytes[0] != 1 || notify_bytes[3] != 4) return fail("unexpected monitor bytes", 0);',
  '  ropendal_monitor_release(monitor);',
  '  ropendal_aio_release(aio);',
  '  ropendal_cv_release(monitor_cv);',
  '',
  '  ropendal_fs_t *fs_uri = 0;',
  '  char uri[4096];',
  '  int uri_len = snprintf(uri, sizeof uri, "fs://%s", argv[1]);',
  '  if (uri_len < 0 || (size_t)uri_len >= sizeof uri) return fail("root uri too long", 0);',
  '  st = ropendal_fs_from_uri(uri, &fs_uri, &err);',
  '  if (st != ROPENDAL_OK) return fail("fs_from_uri failed", err);',
  '  ropendal_read_options_t uri_r = {0};',
  '  uri_r.struct_size = sizeof uri_r;',
  '  uri_r.path = "a.bin";',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs_uri, &uri_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("fs_from_uri read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("fs_from_uri read wait failed", err);',
  '  const uint8_t *uri_bytes = 0;',
  '  size_t uri_len_bytes = 0;',
  '  st = ropendal_aio_result_bytes(aio, &uri_bytes, &uri_len_bytes, &err);',
  '  if (st != ROPENDAL_OK) return fail("fs_from_uri read result failed", err);',
  '  if (uri_len_bytes != 4 || uri_bytes == 0 || uri_bytes[0] != 1 || uri_bytes[3] != 4) return fail("unexpected fs_from_uri bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_fs_release(fs_uri);',
  '',
  '  ropendal_fs_t *http_fs = 0;',
  '  ropendal_kv_t http_kv[2] = {{0}};',
  '  http_kv[0].struct_size = sizeof http_kv[0];',
  '  http_kv[0].key = "endpoint";',
  '  http_kv[0].value = argv[2];',
  '  http_kv[1].struct_size = sizeof http_kv[1];',
  '  http_kv[1].key = "root";',
  '  http_kv[1].value = "/";',
  '  st = ropendal_fs_open("http", http_kv, 2, &http_fs, &err);',
  '  if (st != ROPENDAL_OK) return fail("http fixture open failed", err);',
  '  ropendal_read_options_t cancel_r = {0};',
  '  ropendal_cv_t *cancel_cv = 0;',
  '  struct callback_state cancel_state = {0};',
  '  st = ropendal_cv_alloc(&cancel_cv, &err);',
  '  if (st != ROPENDAL_OK) return fail("cancel callback cv alloc failed", err);',
  '  cancel_state.cv = cancel_cv;',
  '  atomic_init(&cancel_state.aio_addr, (uintptr_t)0);',
  '  atomic_init(&cancel_state.called, 0);',
  '  cancel_r.struct_size = sizeof cancel_r;',
  '  cancel_r.path = "a.bin";',
  '  cancel_r.callback = capture_callback;',
  '  cancel_r.userdata = &cancel_state;',
  '  uint8_t cancel_dst[4] = {9, 9, 9, 9};',
  '  aio = 0;',
  '  st = ropendal_read_into_aio(http_fs, &cancel_r, cancel_dst, sizeof cancel_dst, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("cancel read-into submit failed", err);',
  '  if (ropendal_aio_poll(aio) != ROPENDAL_AIO_PENDING) return fail("cancel read-into was not pending", 0);',
  '  st = ropendal_aio_wait(aio, 0, &err);',
  '  if (st != ROPENDAL_TIMEOUT) return fail("zero-timeout wait did not time out", err);',
  '  ropendal_error_release(err);',
  '  err = 0;',
  '  ropendal_aio_cancel(aio);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_CANCELLED) return fail("cancel wait was not cancelled", err);',
  '  for (int i = 0; i < 100 && atomic_load(&cancel_state.called) == 0; ++i) {',
  '    st = ropendal_cv_until(cancel_cv, 10, &err);',
  '    if (st != ROPENDAL_OK) return fail("cancel callback cv until failed", err);',
  '  }',
  '  if (atomic_load(&cancel_state.called) != 1 || (ropendal_aio_t *)atomic_load(&cancel_state.aio_addr) != aio) return fail("cancel callback did not receive aio", 0);',
  '  if (cancel_dst[0] != 9 || cancel_dst[1] != 9 || cancel_dst[2] != 9 || cancel_dst[3] != 9) return fail("cancelled read-into modified destination", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_cv_release(cancel_cv);',
  '  ropendal_fs_release(http_fs);',
  '',
  '  aio = 0;',
  '  st = ropendal_exists_aio(fs, "a.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("exists submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("exists wait failed", err);',
  '  int exists = 0;',
  '  st = ropendal_aio_result_bool(aio, &exists, &err);',
  '  if (st != ROPENDAL_OK) return fail("exists result failed", err);',
  '  if (exists != 1) return fail("exists result was false", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  st = ropendal_stat_aio(fs, "a.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("stat submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("stat wait failed", err);',
  '  const ropendal_entry_t *entry = 0;',
  '  st = ropendal_aio_result_entry(aio, &entry, &err);',
  '  if (st != ROPENDAL_OK) return fail("stat entry failed", err);',
  '  if (entry == 0 || strcmp(entry->path, "a.bin") != 0) return fail("unexpected stat entry", 0);',
  '  if (entry->has_content_length && entry->content_length != 4) return fail("unexpected stat size", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  st = ropendal_mkdir_aio(fs, "dir", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("mkdir submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("mkdir wait failed", err);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  st = ropendal_copy_aio(fs, "a.bin", "dir/b.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("copy submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("copy wait failed", err);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  st = ropendal_rename_aio(fs, "dir/b.bin", "dir/c.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("rename submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("rename wait failed", err);',
  '  ropendal_aio_release(aio);',
  '',
  '  ropendal_ls_options_t l = {0};',
  '  l.struct_size = sizeof l;',
  '  l.path = "";',
  '  l.recursive = 1;',
  '  aio = 0;',
  '  st = ropendal_ls_aio(fs, &l, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("ls submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("ls wait failed", err);',
  '  const ropendal_entry_t *entries = 0;',
  '  size_t nentries = 0;',
  '  st = ropendal_aio_result_entries(aio, &entries, &nentries, &err);',
  '  if (st != ROPENDAL_OK) return fail("ls entries failed", err);',
  '  int found = 0;',
  '  for (size_t i = 0; i < nentries; ++i) {',
  '    if (strcmp(entries[i].path, "dir/c.bin") == 0) found = 1;',
  '  }',
  '  if (!found) return fail("listed entry not found", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  ropendal_delete_options_t d = {0};',
  '  d.struct_size = sizeof d;',
  '  d.path = "dir/c.bin";',
  '  st = ropendal_delete_aio(fs, &d, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("delete submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("delete wait failed", err);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  st = ropendal_exists_aio(fs, "dir/c.bin", 0, 0, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-delete exists submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-delete exists wait failed", err);',
  '  exists = 1;',
  '  st = ropendal_aio_result_bool(aio, &exists, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-delete exists result failed", err);',
  '  if (exists != 0) return fail("deleted file still exists", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  uint8_t dst[4] = {0, 0, 0, 0};',
  '  ropendal_read_options_t r = {0};',
  '  r.struct_size = sizeof r;',
  '  r.path = "a.bin";',
  '  r.offset = 1;',
  '  r.size = 2;',
  '  r.has_size = 1;',
  '  aio = 0;',
  '  st = ropendal_read_into_aio(fs, &r, dst, sizeof dst, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("read wait failed", err);',
  '  size_t nread = 0;',
  '  st = ropendal_aio_result_nread(aio, &nread, &err);',
  '  if (st != ROPENDAL_OK) return fail("nread failed", err);',
  '  if (nread != 2 || dst[0] != 2 || dst[1] != 3) return fail("unexpected bytes", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("read bytes submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("read bytes wait failed", err);',
  '  const uint8_t *bytes = 0;',
  '  size_t blen = 0;',
  '  st = ropendal_aio_result_bytes(aio, &bytes, &blen, &err);',
  '  if (st != ROPENDAL_OK) return fail("read bytes result failed", err);',
  '  if (blen != 2 || bytes == 0 || bytes[0] != 2 || bytes[1] != 3) return fail("unexpected read bytes result", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  ropendal_readv_options_t rv = {0};',
  '  rv.struct_size = sizeof rv;',
  '  rv.batch_concurrency = 2;',
  '  ropendal_read_request_t read_reqs[2] = {{0}};',
  '  read_reqs[0].struct_size = sizeof read_reqs[0];',
  '  read_reqs[0].path = "a.bin";',
  '  read_reqs[0].offset = 0;',
  '  read_reqs[0].size = 2;',
  '  read_reqs[0].has_size = 1;',
  '  read_reqs[1].struct_size = sizeof read_reqs[1];',
  '  read_reqs[1].path = "a.bin";',
  '  read_reqs[1].offset = 2;',
  '  read_reqs[1].size = 2;',
  '  read_reqs[1].has_size = 1;',
  '  aio = 0;',
  '  st = ropendal_readv_aio(fs, read_reqs, 2, &rv, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes wait failed", err);',
  '  nread = 0;',
  '  st = ropendal_aio_result_nread(aio, &nread, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes nread failed", err);',
  '  const uint8_t *vbytes = 0;',
  '  size_t vlen = 0;',
  '  st = ropendal_aio_result_bytes(aio, &vbytes, &vlen, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes result failed", err);',
  '  if (nread != 4 || vlen != 4 || vbytes == 0 || vbytes[0] != 1 || vbytes[1] != 2 || vbytes[2] != 3 || vbytes[3] != 4) return fail("unexpected readv byte result", 0);',
  '  const ropendal_readv_result_t *rvres = 0;',
  '  size_t nrvres = 0;',
  '  st = ropendal_aio_result_readv(aio, &rvres, &nrvres, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv byte result details failed", err);',
  '  if (nrvres != 2 || rvres[0].index != 0 || rvres[0].status != ROPENDAL_OK || rvres[0].nread != 2 || rvres[1].index != 1 || rvres[1].status != ROPENDAL_OK || rvres[1].nread != 2) return fail("unexpected readv byte result details", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  read_reqs[1].path = "missing.bin";',
  '  aio = 0;',
  '  st = ropendal_readv_aio(fs, read_reqs, 2, &rv, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes partial submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes partial wait failed", err);',
  '  nread = 0;',
  '  st = ropendal_aio_result_nread(aio, &nread, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes partial nread failed", err);',
  '  vbytes = 0; vlen = 0;',
  '  st = ropendal_aio_result_bytes(aio, &vbytes, &vlen, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes partial result failed", err);',
  '  if (nread != 2 || vlen != 2 || vbytes == 0 || vbytes[0] != 1 || vbytes[1] != 2) return fail("unexpected readv partial byte result", 0);',
  '  rvres = 0; nrvres = 0;',
  '  st = ropendal_aio_result_readv(aio, &rvres, &nrvres, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv bytes partial details failed", err);',
  '  if (nrvres != 2 || rvres[0].index != 0 || rvres[0].status != ROPENDAL_OK || rvres[0].nread != 2 || rvres[1].index != 1 || rvres[1].status != ROPENDAL_NOT_FOUND || rvres[1].nread != 0) return fail("unexpected readv bytes partial details", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  uint8_t dstv0[2] = {0, 0};',
  '  uint8_t dstv1[2] = {0, 0};',
  '  ropendal_read_into_request_t reqs[2] = {{0}};',
  '  reqs[0].struct_size = sizeof reqs[0];',
  '  reqs[0].path = "a.bin";',
  '  reqs[0].offset = 0;',
  '  reqs[0].size = 2;',
  '  reqs[0].has_size = 1;',
  '  reqs[0].dst = dstv0;',
  '  reqs[0].dst_len = sizeof dstv0;',
  '  reqs[1].struct_size = sizeof reqs[1];',
  '  reqs[1].path = "a.bin";',
  '  reqs[1].offset = 2;',
  '  reqs[1].size = 2;',
  '  reqs[1].has_size = 1;',
  '  reqs[1].dst = dstv1;',
  '  reqs[1].dst_len = sizeof dstv1;',
  '  aio = 0;',
  '  st = ropendal_readv_into_aio(fs, reqs, 2, &rv, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv wait failed", err);',
  '  nread = 0;',
  '  st = ropendal_aio_result_nread(aio, &nread, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv nread failed", err);',
  '  if (nread != 4 || dstv0[0] != 1 || dstv0[1] != 2 || dstv1[0] != 3 || dstv1[1] != 4) return fail("unexpected readv bytes", 0);',
  '  rvres = 0; nrvres = 0;',
  '  st = ropendal_aio_result_readv(aio, &rvres, &nrvres, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv results failed", err);',
  '  if (nrvres != 2 || rvres[0].status != ROPENDAL_OK || rvres[0].nread != 2 || rvres[1].status != ROPENDAL_OK || rvres[1].nread != 2) return fail("unexpected readv result details", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  dstv0[0] = 0; dstv0[1] = 0; dstv1[0] = 0; dstv1[1] = 0;',
  '  reqs[1].path = "missing.bin";',
  '  aio = 0;',
  '  st = ropendal_readv_into_aio(fs, reqs, 2, &rv, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv partial submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv partial wait failed", err);',
  '  nread = 0;',
  '  st = ropendal_aio_result_nread(aio, &nread, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv partial nread failed", err);',
  '  if (nread != 2 || dstv0[0] != 1 || dstv0[1] != 2) return fail("unexpected readv partial bytes", 0);',
  '  rvres = 0; nrvres = 0;',
  '  st = ropendal_aio_result_readv(aio, &rvres, &nrvres, &err);',
  '  if (st != ROPENDAL_OK) return fail("readv partial results failed", err);',
  '  if (nrvres != 2 || rvres[0].status != ROPENDAL_OK || rvres[0].nread != 2 || rvres[1].status != ROPENDAL_NOT_FOUND || rvres[1].nread != 0) return fail("unexpected readv partial result details", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  const uint8_t replacement[3] = {9, 8, 7};',
  '  aio = 0;',
  '  st = ropendal_replace_aio(fs, &w, replacement, sizeof replacement, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("replace submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("replace wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  uri_r.path = "a.bin";',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &uri_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-replace read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-replace read wait failed", err);',
  '  bytes = 0; blen = 0;',
  '  st = ropendal_aio_result_bytes(aio, &bytes, &blen, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-replace read result failed", err);',
  '  if (blen != 3 || bytes == 0 || bytes[0] != 9 || bytes[1] != 8 || bytes[2] != 7) return fail("unexpected replace bytes", 0);',
  '  ropendal_aio_release(aio);',
  '',
  '  const uint8_t extra[2] = {6, 5};',
  '  aio = 0;',
  '  st = ropendal_append_aio(fs, &w, extra, sizeof extra, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("append submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("append wait failed", err);',
  '  ropendal_aio_release(aio);',
  '  aio = 0;',
  '  st = ropendal_read_aio(fs, &uri_r, &aio, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-append read submit failed", err);',
  '  st = ropendal_aio_wait(aio, -1, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-append read wait failed", err);',
  '  bytes = 0; blen = 0;',
  '  st = ropendal_aio_result_bytes(aio, &bytes, &blen, &err);',
  '  if (st != ROPENDAL_OK) return fail("post-append read result failed", err);',
  '  if (blen != 5 || bytes == 0 || bytes[0] != 9 || bytes[1] != 8 || bytes[2] != 7 || bytes[3] != 6 || bytes[4] != 5) return fail("unexpected append bytes", 0);',
  '  ropendal_aio_release(aio);',
  '  ropendal_fs_release(fs);',
  '  return 0;',
  '}',
  ''
), src)

cmd <- c(
  "-std=c11", "-Wall", "-Wextra", "-Werror",
  "-I", dirname(header), src, lib,
  paste0("-Wl,-rpath,", lib_dir), paste0("-Wl,-rpath,", R.home("lib")),
  "-o", exe
)
out <- system2(cc, cmd, stdout = TRUE, stderr = TRUE)
status <- attr(out, "status")
if (is.null(status)) status <- 0L
if (status != 0L) {
  writeLines(out)
  stop(sprintf("C API roundtrip compile failed with status %s", status), call. = FALSE)
}

env <- Sys.getenv("LD_LIBRARY_PATH", unset = "")
ld <- paste(c(lib_dir, R.home("lib"), env[nzchar(env)]), collapse = ":")
fixture <- Ropendal:::OpendalHttpFixture$start(root, delay_ms = 1000)
on.exit(try(fixture$stop(), silent = TRUE), add = TRUE)
out <- system2(exe, c(root, fixture$endpoint()), stdout = TRUE, stderr = TRUE, env = paste0("LD_LIBRARY_PATH=", ld))
status <- attr(out, "status")
if (is.null(status)) status <- 0L
if (status != 0L) {
  writeLines(out)
  stop(sprintf("C API roundtrip failed with status %s", status), call. = FALSE)
}
cat("C API roundtrip ok\n")
