# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib Ropendal, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_Ropendal__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_Ropendal__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`opendal_bytes_as_raw` <- function(`bytes`) {
  .Call(savvy_opendal_bytes_as_raw__impl, `bytes`)
}


`opendal_bytes_len` <- function(`bytes`) {
  .Call(savvy_opendal_bytes_len__impl, `bytes`)
}

### wrapper functions for OpendalAio

`OpendalAio_cancel` <- function(self) {
  function() {
    .Call(savvy_OpendalAio_cancel__impl, `self`)
  }
}

`OpendalAio_collect` <- function(self) {
  function() {
    .Call(savvy_OpendalAio_collect__impl, `self`)
  }
}

`OpendalAio_error_value` <- function(self) {
  function() {
    .Call(savvy_OpendalAio_error_value__impl, `self`)
  }
}

`OpendalAio_poll` <- function(self) {
  function() {
    .Call(savvy_OpendalAio_poll__impl, `self`)
  }
}

`OpendalAio_state_name` <- function(self) {
  function() {
    .Call(savvy_OpendalAio_state_name__impl, `self`)
  }
}

`.savvy_wrap_OpendalAio` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`cancel` <- `OpendalAio_cancel`(ptr)
  e$`collect` <- `OpendalAio_collect`(ptr)
  e$`error_value` <- `OpendalAio_error_value`(ptr)
  e$`poll` <- `OpendalAio_poll`(ptr)
  e$`state_name` <- `OpendalAio_state_name`(ptr)

  class(e) <- c("Ropendal::OpendalAio", "OpendalAio", "savvy_Ropendal__sealed")
  e
}


#' Asynchronous operation handle.
#' @export
`OpendalAio` <- new.env(parent = emptyenv())

### associated functions for OpendalAio



class(`OpendalAio`) <- c("Ropendal::OpendalAio__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalAio__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalAio\n')
}

### wrapper functions for OpendalBytes


`.savvy_wrap_OpendalBytes` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("Ropendal::OpendalBytes", "OpendalBytes", "savvy_Ropendal__sealed")
  e
}



`OpendalBytes` <- new.env(parent = emptyenv())

### associated functions for OpendalBytes



class(`OpendalBytes`) <- c("Ropendal::OpendalBytes__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalBytes__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalBytes\n')
}

### wrapper functions for OpendalCredentialProvider

`OpendalCredentialProvider_config` <- function(self) {
  function(`service`) {
    .Call(savvy_OpendalCredentialProvider_config__impl, `self`, `service`)
  }
}

`OpendalCredentialProvider_schemes` <- function(self) {
  function() {
    .Call(savvy_OpendalCredentialProvider_schemes__impl, `self`)
  }
}

`OpendalCredentialProvider_summary` <- function(self) {
  function() {
    .Call(savvy_OpendalCredentialProvider_summary__impl, `self`)
  }
}

`.savvy_wrap_OpendalCredentialProvider` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`config` <- `OpendalCredentialProvider_config`(ptr)
  e$`schemes` <- `OpendalCredentialProvider_schemes`(ptr)
  e$`summary` <- `OpendalCredentialProvider_summary`(ptr)

  class(e) <- c("Ropendal::OpendalCredentialProvider", "OpendalCredentialProvider", "savvy_Ropendal__sealed")
  e
}


#' Explicit credential provider.
#' @export
`OpendalCredentialProvider` <- new.env(parent = emptyenv())

### associated functions for OpendalCredentialProvider

`OpendalCredentialProvider`$`gdrive` <- function(`access_token`, `refresh_token`, `client_id`, `client_secret`, `source`) {
  .savvy_wrap_OpendalCredentialProvider(.Call(savvy_OpendalCredentialProvider_gdrive__impl, `access_token`, `refresh_token`, `client_id`, `client_secret`, `source`))
}

`OpendalCredentialProvider`$`gdrive3` <- function(`secret_json`, `tokens_json`, `scope`) {
  .savvy_wrap_OpendalCredentialProvider(.Call(savvy_OpendalCredentialProvider_gdrive3__impl, `secret_json`, `tokens_json`, `scope`))
}

`OpendalCredentialProvider`$`s3` <- function(`access_key_id`, `secret_access_key`, `session_token`, `region`, `source`) {
  .savvy_wrap_OpendalCredentialProvider(.Call(savvy_OpendalCredentialProvider_s3__impl, `access_key_id`, `secret_access_key`, `session_token`, `region`, `source`))
}


class(`OpendalCredentialProvider`) <- c("Ropendal::OpendalCredentialProvider__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalCredentialProvider__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalCredentialProvider\n')
}

### wrapper functions for OpendalFs

`OpendalFs_append` <- function(self) {
  function(`path`, `data`, `batch_concurrency` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .Call(savvy_OpendalFs_append__impl, `self`, `path`, `data`, `batch_concurrency`, `write_concurrency`, `chunk_size`)
  }
}

`OpendalFs_append_aio` <- function(self) {
  function(`path`, `data`, `batch_concurrency` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_append_aio__impl, `self`, `path`, `data`, `batch_concurrency`, `write_concurrency`, `chunk_size`))
  }
}

`OpendalFs_capabilities` <- function(self) {
  function() {
    .Call(savvy_OpendalFs_capabilities__impl, `self`)
  }
}

`OpendalFs_copy` <- function(self) {
  function(`from`, `to`) {
    .Call(savvy_OpendalFs_copy__impl, `self`, `from`, `to`)
  }
}

`OpendalFs_copy_aio` <- function(self) {
  function(`from`, `to`, `batch_concurrency` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_copy_aio__impl, `self`, `from`, `to`, `batch_concurrency`))
  }
}

`OpendalFs_delete` <- function(self) {
  function(`path`, `recursive` = NULL, `batch_concurrency` = NULL) {
    .Call(savvy_OpendalFs_delete__impl, `self`, `path`, `recursive`, `batch_concurrency`)
  }
}

`OpendalFs_delete_aio` <- function(self) {
  function(`path`, `recursive` = NULL, `batch_concurrency` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_delete_aio__impl, `self`, `path`, `recursive`, `batch_concurrency`))
  }
}

`OpendalFs_exists` <- function(self) {
  function(`path`, `batch_concurrency` = NULL) {
    .Call(savvy_OpendalFs_exists__impl, `self`, `path`, `batch_concurrency`)
  }
}

`OpendalFs_exists_aio` <- function(self) {
  function(`path`, `batch_concurrency` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_exists_aio__impl, `self`, `path`, `batch_concurrency`))
  }
}

`OpendalFs_info` <- function(self) {
  function() {
    .Call(savvy_OpendalFs_info__impl, `self`)
  }
}

`OpendalFs_ls` <- function(self) {
  function(`path`, `recursive`) {
    .Call(savvy_OpendalFs_ls__impl, `self`, `path`, `recursive`)
  }
}

`OpendalFs_ls_aio` <- function(self) {
  function(`path`, `recursive`) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_ls_aio__impl, `self`, `path`, `recursive`))
  }
}

`OpendalFs_ls_iter` <- function(self) {
  function(`path`, `recursive` = NULL, `page_size` = NULL) {
    .savvy_wrap_OpendalLsIter(.Call(savvy_OpendalFs_ls_iter__impl, `self`, `path`, `recursive`, `page_size`))
  }
}

`OpendalFs_mkdir` <- function(self) {
  function(`path`) {
    .Call(savvy_OpendalFs_mkdir__impl, `self`, `path`)
  }
}

`OpendalFs_mkdir_aio` <- function(self) {
  function(`path`, `batch_concurrency` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_mkdir_aio__impl, `self`, `path`, `batch_concurrency`))
  }
}

`OpendalFs_normalize_path` <- function(self) {
  function(`path`, `directory`) {
    .Call(savvy_OpendalFs_normalize_path__impl, `self`, `path`, `directory`)
  }
}

`OpendalFs_read` <- function(self) {
  function(`path`, `offset` = NULL, `size` = NULL, `end` = NULL, `result` = NULL, `batch_concurrency` = NULL, `read_concurrency` = NULL, `chunk_size` = NULL, `coalesce_gap` = NULL) {
    .Call(savvy_OpendalFs_read__impl, `self`, `path`, `offset`, `size`, `end`, `result`, `batch_concurrency`, `read_concurrency`, `chunk_size`, `coalesce_gap`)
  }
}

`OpendalFs_read_aio` <- function(self) {
  function(`path`, `offset` = NULL, `size` = NULL, `end` = NULL, `result` = NULL, `batch_concurrency` = NULL, `read_concurrency` = NULL, `chunk_size` = NULL, `coalesce_gap` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_read_aio__impl, `self`, `path`, `offset`, `size`, `end`, `result`, `batch_concurrency`, `read_concurrency`, `chunk_size`, `coalesce_gap`))
  }
}

`OpendalFs_read_bytes` <- function(self) {
  function(`path`, `offset` = NULL, `size` = NULL, `end` = NULL, `result` = NULL, `batch_concurrency` = NULL, `read_concurrency` = NULL, `chunk_size` = NULL, `coalesce_gap` = NULL) {
    .Call(savvy_OpendalFs_read_bytes__impl, `self`, `path`, `offset`, `size`, `end`, `result`, `batch_concurrency`, `read_concurrency`, `chunk_size`, `coalesce_gap`)
  }
}

`OpendalFs_read_bytes_aio` <- function(self) {
  function(`path`, `offset` = NULL, `size` = NULL, `end` = NULL, `result` = NULL, `batch_concurrency` = NULL, `read_concurrency` = NULL, `chunk_size` = NULL, `coalesce_gap` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_read_bytes_aio__impl, `self`, `path`, `offset`, `size`, `end`, `result`, `batch_concurrency`, `read_concurrency`, `chunk_size`, `coalesce_gap`))
  }
}

`OpendalFs_read_iter` <- function(self) {
  function(`path`, `chunk_size`, `offset` = NULL, `size` = NULL, `read_concurrency` = NULL, `coalesce_gap` = NULL) {
    .savvy_wrap_OpendalReadIter(.Call(savvy_OpendalFs_read_iter__impl, `self`, `path`, `chunk_size`, `offset`, `size`, `read_concurrency`, `coalesce_gap`))
  }
}

`OpendalFs_rename` <- function(self) {
  function(`from`, `to`) {
    .Call(savvy_OpendalFs_rename__impl, `self`, `from`, `to`)
  }
}

`OpendalFs_rename_aio` <- function(self) {
  function(`from`, `to`, `batch_concurrency` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_rename_aio__impl, `self`, `from`, `to`, `batch_concurrency`))
  }
}

`OpendalFs_replace` <- function(self) {
  function(`path`, `data`, `batch_concurrency` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .Call(savvy_OpendalFs_replace__impl, `self`, `path`, `data`, `batch_concurrency`, `write_concurrency`, `chunk_size`)
  }
}

`OpendalFs_replace_aio` <- function(self) {
  function(`path`, `data`, `batch_concurrency` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_replace_aio__impl, `self`, `path`, `data`, `batch_concurrency`, `write_concurrency`, `chunk_size`))
  }
}

`OpendalFs_stat` <- function(self) {
  function(`path`, `batch_concurrency` = NULL) {
    .Call(savvy_OpendalFs_stat__impl, `self`, `path`, `batch_concurrency`)
  }
}

`OpendalFs_stat_aio` <- function(self) {
  function(`path`, `batch_concurrency` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_stat_aio__impl, `self`, `path`, `batch_concurrency`))
  }
}

`OpendalFs_walk_iter` <- function(self) {
  function(`path`, `page_size` = NULL) {
    .savvy_wrap_OpendalLsIter(.Call(savvy_OpendalFs_walk_iter__impl, `self`, `path`, `page_size`))
  }
}

`OpendalFs_write` <- function(self) {
  function(`path`, `data`, `batch_concurrency` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .Call(savvy_OpendalFs_write__impl, `self`, `path`, `data`, `batch_concurrency`, `write_concurrency`, `chunk_size`)
  }
}

`OpendalFs_write_aio` <- function(self) {
  function(`path`, `data`, `batch_concurrency` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .savvy_wrap_OpendalAio(.Call(savvy_OpendalFs_write_aio__impl, `self`, `path`, `data`, `batch_concurrency`, `write_concurrency`, `chunk_size`))
  }
}

`OpendalFs_write_iter` <- function(self) {
  function(`path`, `create` = NULL, `append` = NULL, `write_concurrency` = NULL, `chunk_size` = NULL) {
    .savvy_wrap_OpendalWriteIter(.Call(savvy_OpendalFs_write_iter__impl, `self`, `path`, `create`, `append`, `write_concurrency`, `chunk_size`))
  }
}

`.savvy_wrap_OpendalFs` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`append` <- `OpendalFs_append`(ptr)
  e$`append_aio` <- `OpendalFs_append_aio`(ptr)
  e$`capabilities` <- `OpendalFs_capabilities`(ptr)
  e$`copy` <- `OpendalFs_copy`(ptr)
  e$`copy_aio` <- `OpendalFs_copy_aio`(ptr)
  e$`delete` <- `OpendalFs_delete`(ptr)
  e$`delete_aio` <- `OpendalFs_delete_aio`(ptr)
  e$`exists` <- `OpendalFs_exists`(ptr)
  e$`exists_aio` <- `OpendalFs_exists_aio`(ptr)
  e$`info` <- `OpendalFs_info`(ptr)
  e$`ls` <- `OpendalFs_ls`(ptr)
  e$`ls_aio` <- `OpendalFs_ls_aio`(ptr)
  e$`ls_iter` <- `OpendalFs_ls_iter`(ptr)
  e$`mkdir` <- `OpendalFs_mkdir`(ptr)
  e$`mkdir_aio` <- `OpendalFs_mkdir_aio`(ptr)
  e$`normalize_path` <- `OpendalFs_normalize_path`(ptr)
  e$`read` <- `OpendalFs_read`(ptr)
  e$`read_aio` <- `OpendalFs_read_aio`(ptr)
  e$`read_bytes` <- `OpendalFs_read_bytes`(ptr)
  e$`read_bytes_aio` <- `OpendalFs_read_bytes_aio`(ptr)
  e$`read_iter` <- `OpendalFs_read_iter`(ptr)
  e$`rename` <- `OpendalFs_rename`(ptr)
  e$`rename_aio` <- `OpendalFs_rename_aio`(ptr)
  e$`replace` <- `OpendalFs_replace`(ptr)
  e$`replace_aio` <- `OpendalFs_replace_aio`(ptr)
  e$`stat` <- `OpendalFs_stat`(ptr)
  e$`stat_aio` <- `OpendalFs_stat_aio`(ptr)
  e$`walk_iter` <- `OpendalFs_walk_iter`(ptr)
  e$`write` <- `OpendalFs_write`(ptr)
  e$`write_aio` <- `OpendalFs_write_aio`(ptr)
  e$`write_iter` <- `OpendalFs_write_iter`(ptr)

  class(e) <- c("Ropendal::OpendalFs", "OpendalFs", "savvy_Ropendal__sealed")
  e
}


#' Filesystem handle backed by Apache OpenDAL.
#' @export
`OpendalFs` <- new.env(parent = emptyenv())

### associated functions for OpendalFs

`OpendalFs`$`from_uri` <- function(`uri`, `headers` = NULL) {
  .savvy_wrap_OpendalFs(.Call(savvy_OpendalFs_from_uri__impl, `uri`, `headers`))
}

`OpendalFs`$`open` <- function(`scheme`, `dots`, `config`, `root` = NULL, `auth_config` = NULL, `headers` = NULL) {
  .savvy_wrap_OpendalFs(.Call(savvy_OpendalFs_open__impl, `scheme`, `dots`, `config`, `root`, `auth_config`, `headers`))
}


class(`OpendalFs`) <- c("Ropendal::OpendalFs__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalFs__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalFs\n')
}

### wrapper functions for OpendalHttpFixture

`OpendalHttpFixture_endpoint` <- function(self) {
  function() {
    .Call(savvy_OpendalHttpFixture_endpoint__impl, `self`)
  }
}

`OpendalHttpFixture_root` <- function(self) {
  function() {
    .Call(savvy_OpendalHttpFixture_root__impl, `self`)
  }
}

`OpendalHttpFixture_stop` <- function(self) {
  function() {
    .Call(savvy_OpendalHttpFixture_stop__impl, `self`)
  }
}

`.savvy_wrap_OpendalHttpFixture` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`endpoint` <- `OpendalHttpFixture_endpoint`(ptr)
  e$`root` <- `OpendalHttpFixture_root`(ptr)
  e$`stop` <- `OpendalHttpFixture_stop`(ptr)

  class(e) <- c("Ropendal::OpendalHttpFixture", "OpendalHttpFixture", "savvy_Ropendal__sealed")
  e
}


#' Internal HTTP fixture for tests.
#' @export
`OpendalHttpFixture` <- new.env(parent = emptyenv())

### associated functions for OpendalHttpFixture

`OpendalHttpFixture`$`start` <- function(`root`, `required_headers` = NULL, `delay_ms` = NULL) {
  .savvy_wrap_OpendalHttpFixture(.Call(savvy_OpendalHttpFixture_start__impl, `root`, `required_headers`, `delay_ms`))
}


class(`OpendalHttpFixture`) <- c("Ropendal::OpendalHttpFixture__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalHttpFixture__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalHttpFixture\n')
}

### wrapper functions for OpendalLsIter

`OpendalLsIter_collect` <- function(self) {
  function() {
    .Call(savvy_OpendalLsIter_collect__impl, `self`)
  }
}

`OpendalLsIter_next` <- function(self) {
  function() {
    .Call(savvy_OpendalLsIter_next__impl, `self`)
  }
}

`.savvy_wrap_OpendalLsIter` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`collect` <- `OpendalLsIter_collect`(ptr)
  e$`next` <- `OpendalLsIter_next`(ptr)

  class(e) <- c("Ropendal::OpendalLsIter", "OpendalLsIter", "savvy_Ropendal__sealed")
  e
}


#' Streaming listing iterator over one prefix.
#' @export
`OpendalLsIter` <- new.env(parent = emptyenv())

### associated functions for OpendalLsIter



class(`OpendalLsIter`) <- c("Ropendal::OpendalLsIter__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalLsIter__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalLsIter\n')
}

### wrapper functions for OpendalReadIter

`OpendalReadIter_collect` <- function(self) {
  function() {
    .Call(savvy_OpendalReadIter_collect__impl, `self`)
  }
}

`OpendalReadIter_next` <- function(self) {
  function() {
    .Call(savvy_OpendalReadIter_next__impl, `self`)
  }
}

`OpendalReadIter_seek` <- function(self) {
  function(`offset`, `whence` = NULL) {
    .Call(savvy_OpendalReadIter_seek__impl, `self`, `offset`, `whence`)
  }
}

`OpendalReadIter_tell` <- function(self) {
  function() {
    .Call(savvy_OpendalReadIter_tell__impl, `self`)
  }
}

`.savvy_wrap_OpendalReadIter` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`collect` <- `OpendalReadIter_collect`(ptr)
  e$`next` <- `OpendalReadIter_next`(ptr)
  e$`seek` <- `OpendalReadIter_seek`(ptr)
  e$`tell` <- `OpendalReadIter_tell`(ptr)

  class(e) <- c("Ropendal::OpendalReadIter", "OpendalReadIter", "savvy_Ropendal__sealed")
  e
}


#' Chunked read iterator over one object.
#' @export
`OpendalReadIter` <- new.env(parent = emptyenv())

### associated functions for OpendalReadIter



class(`OpendalReadIter`) <- c("Ropendal::OpendalReadIter__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalReadIter__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalReadIter\n')
}

### wrapper functions for OpendalWriteIter

`OpendalWriteIter_close` <- function(self) {
  function() {
    .Call(savvy_OpendalWriteIter_close__impl, `self`)
  }
}

`OpendalWriteIter_tell` <- function(self) {
  function() {
    .Call(savvy_OpendalWriteIter_tell__impl, `self`)
  }
}

`OpendalWriteIter_write` <- function(self) {
  function(`data`) {
    .Call(savvy_OpendalWriteIter_write__impl, `self`, `data`)
  }
}

`.savvy_wrap_OpendalWriteIter` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`close` <- `OpendalWriteIter_close`(ptr)
  e$`tell` <- `OpendalWriteIter_tell`(ptr)
  e$`write` <- `OpendalWriteIter_write`(ptr)

  class(e) <- c("Ropendal::OpendalWriteIter", "OpendalWriteIter", "savvy_Ropendal__sealed")
  e
}


#' Chunked write sink for one object.
#' @export
`OpendalWriteIter` <- new.env(parent = emptyenv())

### associated functions for OpendalWriteIter



class(`OpendalWriteIter`) <- c("Ropendal::OpendalWriteIter__bundle", "savvy_Ropendal__sealed")

#' @export
`print.Ropendal::OpendalWriteIter__bundle` <- function(x, ...) {
  cat('Ropendal::OpendalWriteIter\n')
}

